using System.Collections.Generic;
using Pulumi;

namespace Ceteris.Extensions
{
    class StackExtensions
    {
        public static ResourceTransformation RegisterAutoTags(Dictionary<string, string> autoTags) 
        {
            return args => {
                if (IsTaggable(args.Resource.GetResourceType()))
                {
                    // Use reflection to look up the Tags property and merge the auto-tags.
                    var tagp = args.Args.GetType().GetProperty("Tags");
                    var tags = tagp != null ? (InputMap<string>)tagp.GetValue(args.Args,null) : new InputMap<string>();
                    foreach (var tag in autoTags) {
                        tags[tag.Key] = tag.Value;
                    }
                    tagp.SetValue(args.Args, tags, null);
                    return new ResourceTransformationResult(args.Args, args.Options);
                }
                return null;
            };
        }

        public static ResourceTransformation ProtectProdResources(string stackName)
        {
            return res => {
                // check, if the resource definition already contains a protected tag
                var isProtected = res.Options.GetType().GetProperty("Protect").GetValue(res.Options) ?? false;
                var isProdEnvironmentOrProtected = stackName.ToLower() == "prod" ? true : (bool)isProtected ? true : false;

                //set the final value depending on input and environment
                res.Options.GetType().GetProperty("Protect").SetValue(res.Options, isProdEnvironmentOrProtected);
                return new ResourceTransformationResult(res.Args, res.Options);
            };
        }

        public static string RetrieveRoleDefinitionId (string roleName, string subscriptionId)
        {
            string? result;
            var test = standardAzureRoles.TryGetValue(roleName, out result);
            if (test)
            {
                return $"/subscriptions/{subscriptionId}/providers/Microsoft.Authorization/roleDefinitions/{standardAzureRoles[roleName]}";
            }
            else
            {
                throw new System.ArgumentException("Provide a valid azure role name!");
            }
        }

        private static bool IsTaggable(string type)
        {
            foreach (string taggableType in taggableResourceTypes) {
                if (type == taggableType) {
                    return true;
                }
            }
            return false;
        }

        // taggableResourceTypes is a list of computed Azure type tokens that are taggable.
        // WARNING: The list might contain errors. Check carefully all of your created resources!
        private static string[] taggableResourceTypes = {
            "azure-native:aad:DomainService",
            "azure-native:agfoodplatform:FarmBeat",
            "azure-native:alertsmanagement:ActionRule",
            "azure-native:alertsmanagement:ResourceHealthAlertRule",
            "azure-native:alertsmanagement:SmartDetectorAlertRule",
            "azure-native:analysisservices:Server",
            "azure-native:anybuild:Cluster",
            "azure-native:apimanagement:Service",
            "azure-native:appassessment:MigrateProject",
            "azure-native:appconfiguration:ConfigurationStore",
            "azure-native:appplatform:Spring",
            "azure-native:attestation:AttestationProvider",
            "azure-native:authorization:ResourceManagementPrivateLink",
            "azure-native:automanage:Account",
            "azure-native:automanage:ConfigurationProfilePreference",
            "azure-native:automation:AutomationAccount",
            "azure-native:automation:AutomationAccounts/configuration",
            "azure-native:automation:AutomationAccounts/runbook",
            "azure-native:avs:PrivateCloud",
            "azure-native:azureactivedirectory:B2cDirectorie",
            "azure-native:azureactivedirectory:GuestUsage",
            "azure-native:azurearcdata:DataController",
            "azure-native:azurearcdata:DataWarehouseInstance",
            "azure-native:azurearcdata:PostgresInstance",
            "azure-native:azurearcdata:SqlManagedInstance",
            "azure-native:azurearcdata:SqlServerInstance",
            "azure-native:azurecis:AutopilotEnvironment",
            "azure-native:azuredata:SqlServerRegistration",
            "azure-native:azuresphere:Catalog",
            "azure-native:azuresphere:Catalogs/product",
            "azure-native:azurestack:EdgeSubscription",
            "azure-native:azurestack:LinkedSubscription",
            "azure-native:azurestack:Registration",
            "azure-native:azurestackhci:Cluster",
            "azure-native:azurestackhci:GalleryImage",
            "azure-native:azurestackhci:NetworkInterface",
            "azure-native:azurestackhci:VirtualHardDisk",
            "azure-native:azurestackhci:VirtualMachine",
            "azure-native:azurestackhci:VirtualNetwork",
            "azure-native:baremetalinfrastructure:BareMetalInstance",
            "azure-native:batch:BatchAccount",
            "azure-native:bingmaps:MapApi",
            "azure-native:blockchain:BlockchainMember",
            "azure-native:blockchain:CordaMember",
            "azure-native:blockchain:Watcher",
            "azure-native:blockchaintokens:TokenService",
            "azure-native:botservice:BotService",
            "azure-native:cache:Redi",
            "azure-native:cache:RedisEnterprise",
            "azure-native:cascade:Site",
            "azure-native:cdn:CdnWebApplicationFirewallPolicie",
            "azure-native:cdn:Profile",
            "azure-native:cdn:Profiles/afdendpoint",
            "azure-native:cdn:Profiles/endpoint",
            "azure-native:certificateregistration:CertificateOrder",
            "azure-native:clusterstor:Node",
            "azure-native:codespaces:Plan",
            "azure-native:cognitiveservices:Account",
            "azure-native:connectedcache:CacheNode",
            "azure-native:compute:AvailabilitySet",
            "azure-native:compute:CloudService",
            "azure-native:compute:DiskAccesse",
            "azure-native:compute:DiskEncryptionSet",
            "azure-native:compute:Disk",
            "azure-native:compute:Gallerie",
            "azure-native:compute:HostGroup",
            "azure-native:compute:HostGroups/host",
            "azure-native:compute:Image",
            "azure-native:compute:ProximityPlacementGroup",
            "azure-native:compute:RestorePointCollection",
            "azure-native:compute:SharedVMExtension",
            "azure-native:compute:SharedVMImage",
            "azure-native:compute:Snapshot",
            "azure-native:compute:SshPublicKey",
            "azure-native:compute:VirtualMachine",
            "azure-native:compute:VirtualMachines/extension",
            "azure-native:compute:VirtualMachines/runCommand",
            "azure-native:compute:VirtualMachineScaleSet",
            "azure-native:compute:VirtualMachineScaleSets/publicIPAddresse",
            "azure-native:connectedvehicle:PlatformAccount",
            "azure-native:connectedvmwarevsphere:ResourcePool",
            "azure-native:connectedvmwarevsphere:VCenter",
            "azure-native:connectedvmwarevsphere:VirtualMachine",
            "azure-native:connectedvmwarevsphere:VirtualMachines/Extension",
            "azure-native:connectedvmwarevsphere:VirtualMachineTemplate",
            "azure-native:connectedvmwarevsphere:VirtualNetwork",
            "azure-native:containerinstance:ContainerGroup",
            "azure-native:containerregistry:Registrie",
            "azure-native:containerregistry:Registries/agentPool",
            "azure-native:containerregistry:Registries/buildTask",
            "azure-native:containerregistry:Registries/replication",
            "azure-native:containerregistry:Registries/task",
            "azure-native:containerregistry:Registries/webhook",
            "azure-native:containerservice:ContainerService",
            "azure-native:containerservice:ManagedCluster",
            "azure-native:containerservice:OpenShiftManagedCluster",
            "azure-native:costmanagement:Connector",
            "azure-native:customproviders:ResourceProvider",
            "azure-native:d365customerinsights:Instance",
            "azure-native:databox:Job",
            "azure-native:databoxedge:DataBoxEdgeDevice",
            "azure-native:databricks:Workspace",
            "azure-native:datacatalog:Catalog",
            "azure-native:datafactory:Factory",
            "azure-native:datalakeanalytics:Account",
            "azure-native:datalakestore:Account",
            "azure-native:datamigration:SqlMigrationService",
            "azure-native:dataprotection:BackupVault",
            "azure-native:dataprotection:ResourceGuard",
            "azure-native:datashare:Account",
            "azure-native:dbformariadb:Server",
            "azure-native:dbformysql:FlexibleServer",
            "azure-native:dbformysql:Server",
            "azure-native:dbforpostgresql:FlexibleServer",
            "azure-native:dbforpostgresql:ServerGroup",
            "azure-native:dbforpostgresql:ServerGroupsv2",
            "azure-native:dbforpostgresql:Server",
            "azure-native:dbforpostgresql:Serversv2",
            "azure-native:deploymentmanager:ArtifactSource",
            "azure-native:deploymentmanager:Rollout",
            "azure-native:deploymentmanager:ServiceTopologie",
            "azure-native:deploymentmanager:ServiceTopologies/service",
            "azure-native:deploymentmanager:ServiceTopologies/services/serviceUnit",
            "azure-native:deploymentmanager:Step",
            "azure-native:desktopvirtualization:Applicationgroup",
            "azure-native:desktopvirtualization:Hostpool",
            "azure-native:desktopvirtualization:ScalingPlan",
            "azure-native:desktopvirtualization:Workspace",
            "azure-native:devices:ElasticPool",
            "azure-native:devices:ElasticPools/IotHubTenant",
            "azure-native:devices:IotHub",
            "azure-native:devices:ProvisioningService",
            "azure-native:deviceupdate:Account",
            "azure-native:deviceupdate:Accounts/instance",
            "azure-native:devops:Pipeline",
            "azure-native:devspaces:Controller",
            "azure-native:devtestlab:Labcenter",
            "azure-native:devtestlab:Lab",
            "azure-native:devtestlab:Labs/environment",
            "azure-native:devtestlab:Labs/serviceRunner",
            "azure-native:devtestlab:Labs/virtualMachine",
            "azure-native:devtestlab:Schedule",
            "azure-native:digitaltwins:DigitalTwinsInstance",
            "azure-native:documentdb:CassandraCluster",
            "azure-native:documentdb:DatabaseAccount",
            "azure-native:domainregistration:Domain",
            "azure-native:edgeorder:Addresse",
            "azure-native:edgeorder:OrderCollection",
            "azure-native:edgeorder:Order",
            "azure-native:enterpriseknowledgegraph:Service",
            "azure-native:eventgrid:Domain",
            "azure-native:eventgrid:PartnerNamespace",
            "azure-native:eventgrid:PartnerRegistration",
            "azure-native:eventgrid:PartnerTopic",
            "azure-native:eventgrid:SystemTopic",
            "azure-native:eventgrid:Topic",
            "azure-native:eventhub:Cluster",
            "azure-native:eventhub:Namespace",
            "azure-native:experimentation:ExperimentWorkspace",
            "azure-native:falcon:Namespace",
            "azure-native:genomics:Account",
            "azure-native:guestconfiguration:AutoManagedAccount",
            "azure-native:guestconfiguration:AutoManagedVmConfigurationProfile",
            "azure-native:hanaonazure:HanaInstance",
            "azure-native:hanaonazure:SapMonitor",
            "azure-native:hardwaresecuritymodules:DedicatedHSM",
            "azure-native:hdinsight:ClusterPool",
            "azure-native:hdinsight:ClusterPools/cluster",
            "azure-native:hdinsight:Cluster",
            "azure-native:healthbot:HealthBot",
            "azure-native:healthcareapis:Service",
            "azure-native:healthcareapis:Workspace",
            "azure-native:healthcareapis:Workspaces/dicomservice",
            "azure-native:hybridcompute:Machine",
            "azure-native:hybridcompute:Machines/extension",
            "azure-native:hybridcompute:PrivateLinkScope",
            "azure-native:hybriddata:DataManager",
            "azure-native:hybridnetwork:Device",
            "azure-native:hybridnetwork:Networkfunction",
            "azure-native:hybridnetwork:VirtualNetworkFunction",
            "azure-native:hydra:Component",
            "azure-native:hydra:NetworkScope",
            "azure-native:importexport:Job",
            "azure-native:insights:ActionGroup",
            "azure-native:insights:ActivityLogAlert",
            "azure-native:insights:Alertrule",
            "azure-native:insights:Autoscalesetting",
            "azure-native:insights:Component",
            "azure-native:insights:GuestDiagnosticSetting",
            "azure-native:insights:GuestDiagnosticSettingsAssociation",
            "azure-native:insights:Logprofile",
            "azure-native:insights:MetricAlert",
            "azure-native:insights:PrivateLinkScope",
            "azure-native:insights:QueryPack",
            "azure-native:insights:ScheduledQueryRule",
            "azure-native:insights:Webtest",
            "azure-native:insights:Workbook",
            "azure-native:insights:Workbooktemplate",
            "azure-native:iotcentral:IoTApp",
            "azure-native:iotspaces:Graph",
            "azure-native:keyvault:HsmPool",
            "azure-native:keyvault:ManagedHSM",
            "azure-native:keyvault:Vault",
            "azure-native:kubernetes:ConnectedCluster",
            "azure-native:kusto:Cluster",
            "azure-native:labservices:Labaccount",
            "azure-native:labservices:Labplan",
            "azure-native:labservices:Lab",
            "azure-native:logic:HostingEnvironment",
            "azure-native:logic:IntegrationAccount",
            "azure-native:logic:IntegrationServiceEnvironment",
            "azure-native:logic:IsolatedEnvironment",
            "azure-native:logic:Workflow",
            "azure-native:machinelearning:CommitmentPlan",
            "azure-native:machinelearning:WebService",
            "azure-native:machinelearning:Workspace",
            "azure-native:machinelearningservices:Modelinventorie",
            "azure-native:machinelearningservices:Virtualcluster",
            "azure-native:machinelearningservices:Workspace",
            "azure-native:machinelearningservices:Workspaces/batchEndpoint",
            "azure-native:machinelearningservices:Workspaces/batchEndpoints/deployment",
            "azure-native:machinelearningservices:Workspaces/onlineEndpoint",
            "azure-native:machinelearningservices:Workspaces/onlineEndpoints/deployment",
            "azure-native:maintenance:MaintenanceConfiguration",
            "azure-native:managedidentity:UserAssignedIdentitie",
            "azure-native:managednetwork:ManagedNetwork",
            "azure-native:managednetwork:ManagedNetworks/managedNetworkGroup",
            "azure-native:managednetwork:ManagedNetworks/managedNetworkPeeringPolicie",
            "azure-native:managednetwork:Notification",
            "azure-native:maps:Account",
            "azure-native:maps:Accounts/creator",
            "azure-native:maps:Accounts/privateAtlase",
            "azure-native:marketplaceapps:ClassicDevService",
            "azure-native:media:Mediaservice",
            "azure-native:media:Mediaservices/liveEvent",
            "azure-native:media:Mediaservices/streamingEndpoint",
            "azure-native:media:VideoAnalyzer",
            "azure-native:microservices4spring:AppCluster",
            "azure-native:migrate:AssessmentProject",
            "azure-native:migrate:Migrateproject",
            "azure-native:migrate:MoveCollection",
            "azure-native:migrate:Project",
            "azure-native:mixedreality:HolographicsBroadcastAccount",
            "azure-native:mixedreality:ObjectAnchorsAccount",
            "azure-native:mixedreality:ObjectUnderstandingAccount",
            "azure-native:mixedreality:RemoteRenderingAccount",
            "azure-native:mixedreality:SpatialAnchorsAccount",
            "azure-native:mobilenetwork:Network",
            "azure-native:mobilenetwork:Networks/site",
            "azure-native:mobilenetwork:PacketCore",
            "azure-native:mobilenetwork:Sim",
            "azure-native:mobilenetwork:Sims/simProfile",
            "azure-native:netapp:NetAppAccount",
            "azure-native:netapp:NetAppAccounts/capacityPool",
            "azure-native:netapp:NetAppAccounts/capacityPools/volume",
            "azure-native:network:ApplicationGateway",
            "azure-native:network:ApplicationGatewayWebApplicationFirewallPolicie",
            "azure-native:network:ApplicationSecurityGroup",
            "azure-native:network:AzureFirewall",
            "azure-native:network:BastionHost",
            "azure-native:network:Connection",
            "azure-native:network:DdosCustomPolicie",
            "azure-native:network:DdosProtectionPlan",
            "azure-native:network:Dnszone",
            "azure-native:network:ExpressRouteCircuit",
            "azure-native:network:ExpressRouteCrossConnection",
            "azure-native:network:ExpressRouteGateway",
            "azure-native:network:ExpressRoutePort",
            "azure-native:network:FirewallPolicie",
            "azure-native:network:Frontdoor",
            "azure-native:network:FrontdoorWebApplicationFirewallManagedRuleSet",
            "azure-native:network:FrontdoorWebApplicationFirewallPolicie",
            "azure-native:network:IpGroup",
            "azure-native:network:LoadBalancer",
            "azure-native:network:LocalNetworkGateway",
            "azure-native:network:NatGateway",
            "azure-native:network:NetworkIntentPolicie",
            "azure-native:network:NetworkInterface",
            "azure-native:network:NetworkProfile",
            "azure-native:network:NetworkSecurityGroup",
            "azure-native:network:NetworkWatcher",
            "azure-native:network:NetworkWatchers/connectionMonitor",
            "azure-native:network:NetworkWatchers/flowLog",
            "azure-native:network:NetworkWatchers/lense",
            "azure-native:network:NetworkWatchers/pingMeshe",
            "azure-native:network:P2sVpnGateway",
            "azure-native:network:PrivateDnsZone",
            "azure-native:network:PrivateDnsZones/virtualNetworkLink",
            "azure-native:network:PrivateEndpoint",
            "azure-native:network:PrivateLinkService",
            "azure-native:network:PublicIPAddresse",
            "azure-native:network:PublicIPPrefixe",
            "azure-native:network:RouteFilter",
            "azure-native:network:RouteTable",
            "azure-native:network:ServiceEndpointPolicie",
            "azure-native:network:Trafficmanagerprofile",
            "azure-native:network:VirtualHub",
            "azure-native:network:VirtualNetworkGateway",
            "azure-native:network:VirtualNetwork",
            "azure-native:network:VirtualNetworkTap",
            "azure-native:network:VirtualWan",
            "azure-native:network:VpnGateway",
            "azure-native:network:VpnSite",
            "azure-native:network:WebApplicationFirewallPolicie",
            "azure-native:notificationhubs:Namespace",
            "azure-native:notificationhubs:Namespaces/notificationHub",
            "azure-native:objectstore:OsNamespace",
            "azure-native:offazure:HyperVSite",
            "azure-native:offazure:ImportSite",
            "azure-native:offazure:MasterSite",
            "azure-native:offazure:ServerSite",
            "azure-native:offazure:VMwareSite",
            "azure-native:operationalinsights:Cluster",
            "azure-native:operationalinsights:Querypack",
            "azure-native:operationalinsights:Workspace",
            "azure-native:operationsmanagement:Managementconfiguration",
            "azure-native:operationsmanagement:Solution",
            "azure-native:operationsmanagement:View",
            "azure-native:peering:Peering",
            "azure-native:peering:PeeringService",
            "azure-native:portal:Dashboard",
            "azure-native:powerbi:PrivateLinkServicesForPowerBI",
            "azure-native:powerbi:Tenant",
            "azure-native:powerbi:WorkspaceCollection",
            "azure-native:powerbidedicated:AutoScaleVCore",
            "azure-native:powerbidedicated:Capacitie",
            "azure-native:powerplatform:EnterprisePolicie",
            "azure-native:projectbabylon:Account",
            "azure-native:purview:Account",
            "azure-native:quantum:Workspace",
            "azure-native:recoveryservices:Vault",
            "azure-native:redhatopenshift:OpenShiftCluster",
            "azure-native:relay:Namespace",
            "azure-native:resourceconnector:Appliance",
            "azure-native:resourcegraph:Querie",
            "azure-native:resources:Deployment",
            "azure-native:resources:DeploymentScript",
            "azure-native:resources:ResourceGroup",
            "azure-native:resources:Subscription",
            "azure-native:resources:TemplateSpec",
            "azure-native:resources:TemplateSpecs/version",
            "azure-native:saas:Application",
            "azure-native:saas:Resource",
            "azure-native:scvmm:Cloud",
            "azure-native:scvmm:VirtualMachine",
            "azure-native:scvmm:VirtualMachineTemplate",
            "azure-native:scvmm:VirtualNetwork",
            "azure-native:scvmm:Vmmserver",
            "azure-native:search:SearchService",
            "azure-native:security:Automation",
            "azure-native:security:IotSecuritySolution",
            "azure-native:servicebus:Namespace",
            "azure-native:servicefabric:Application",
            "azure-native:servicefabric:Cluster",
            "azure-native:servicefabric:ContainerGroup",
            "azure-native:servicefabric:ContainerGroupSet",
            "azure-native:servicefabric:Edgecluster",
            "azure-native:servicefabric:Managedcluster",
            "azure-native:servicefabric:Network",
            "azure-native:servicefabric:Secretstore",
            "azure-native:servicefabric:Volume",
            "azure-native:servicefabricmesh:Application",
            "azure-native:servicefabricmesh:ContainerGroup",
            "azure-native:servicefabricmesh:Gateway",
            "azure-native:servicefabricmesh:Network",
            "azure-native:servicefabricmesh:Secret",
            "azure-native:servicefabricmesh:Volume",
            "azure-native:services:Rollout",
            "azure-native:signalrservice:SignalR",
            "azure-native:signalrservice:WebPubSub",
            "azure-native:singularity:Account",
            "azure-native:solutions:ApplicationDefinition",
            "azure-native:solutions:Application",
            "azure-native:solutions:JitRequest",
            "azure-native:sql:ManagedInstance",
            "azure-native:sql:Server",
            "azure-native:sql:Database",
            "azure-native:sqlvirtualmachine:SqlVirtualMachineGroup",
            "azure-native:sqlvirtualmachine:SqlVirtualMachine",
            "azure-native:storage:StorageAccount",
            "azure-native:storagecache:AmlFilesystem",
            "azure-native:storagecache:Cache",
            "azure-native:storagesync:StorageSyncService",
            "azure-native:storagesyncdev:StorageSyncService",
            "azure-native:storagesyncint:StorageSyncService",
            "azure-native:storsimple:Manager",
            "azure-native:streamanalytics:Cluster",
            "azure-native:streamanalytics:Streamingjob",
            "azure-native:synapse:PrivateLinkHub",
            "azure-native:synapse:Workspace",
            "azure-native:synapse:Workspaces/bigDataPool",
            "azure-native:synapse:Workspaces/sqlDatabase",
            "azure-native:synapse:Workspaces/sqlPool",
            "azure-native:timeseriesinsights:Environment",
            "azure-native:timeseriesinsights:Environments/eventsource",
            "azure-native:timeseriesinsights:Environments/referenceDataSet",
            "azure-native:token:Store",
            "azure-native:virtualmachineimages:ImageTemplate",
            "azure-native:vmware:ArcZone",
            "azure-native:vmware:ResourcePool",
            "azure-native:vmware:VCenter",
            "azure-native:vmware:Virtualmachine",
            "azure-native:vmware:VirtualMachineTemplate",
            "azure-native:vmware:VirtualNetwork",
            "azure-native:vmwarecloudsimple:DedicatedCloudNode",
            "azure-native:vmwarecloudsimple:DedicatedCloudService",
            "azure-native:vmwarecloudsimple:VirtualMachine",
            "azure-native:vnfmanager:Device",
            "azure-native:vnfmanager:Vnf",
            "azure-native:vsonline:Account",
            "azure-native:vsonline:Plan",
            "azure-native:web:Certificate",
            "azure-native:web:ConnectionGateway",
            "azure-native:web:Connection",
            "azure-native:web:CustomApi",
            "azure-native:web:HostingEnvironment",
            "azure-native:web:KubeEnvironment",
            "azure-native:web:ServerFarm",
            "azure-native:web:Site",
            "azure-native:web:Sites/premieraddon",
            "azure-native:web:Sites/slot",
            "azure-native:web:StaticSite",
            "azure-native:windowsesu:MultipleActivationKey",
            "azure-native:windowsiot:DeviceService",
            "azure-native:workloadbuilder:MigrationAgent",
            "azure-native:workloadbuilder:Workload",


        };

        public static Dictionary<string,string> standardAzureRoles = new Dictionary<string, string>
        {
            { "Contributor" , "b24988ac-6180-42a0-ab88-20f7382dd24c" },
            { "Owner" , "8e3af657-a8ff-443c-a75c-2fe8c4bcb635" },
            { "Reader" , "acdd72a7-3385-48ef-bd42-f606fba81ae7" },
            { "User Access Administrator" , "18d7d88d-d35e-4fb5-a5c3-7773c20a72d9" },
            { "Classic Virtual Machine Contributor" , "d73bb868-a0df-4d4d-bd69-98a00b01fccb" },
            { "Virtual Machine Administrator Login" , "1c0163c0-47e6-4577-8991-ea5c82e286e4" },
            { "Virtual Machine Contributor" , "9980e02c-c2be-4d73-94e8-173b1dc7cf3c" },
            { "Virtual Machine User Login" , "fb879df8-f326-4884-b1cf-06f3ad86be52" },
            { "CDN Endpoint Contributor" , "426e0c7f-0c7e-4658-b36f-ff54d6c29b45" },
            { "CDN Endpoint Reader" , "871e35f6-b5c1-49cc-a043-bde969a0f2cd" },
            { "CDN Profile Contributor" , "ec156ff8-a8d1-4d15-830c-5b80698ca432" },
            { "CDN Profile Reader" , "8f96442b-4075-438f-813d-ad51ab4019af" },
            { "Classic Network Contributor" , "b34d265f-36f7-4a0d-a4d4-e158ca92e90f" },
            { "DNS Zone Contributor" , "befefa01-2a29-4197-83a8-272ff33ce314" },
            { "Network Contributor" , "4d97b98b-1d4f-4787-a291-c67834d212e7" },
            { "Private DNS Zone Contributor" , "b12aa53e-6015-4669-85d0-8515ebb3ae7f" },
            { "Traffic Manager Contributor" , "a4b10055-b0c7-44c2-b00f-c7b5b3550cf7" },
            { "Avere Contributor" , "4f8fab4f-1852-4a58-a46a-8eaf358af14a" },
            { "Avere Operator" , "c025889f-8102-4ebf-b32c-fc0c6f0c6bd9" },
            { "Backup Contributor" , "5e467623-bb1f-42f4-a55d-6e525e11384b" },
            { "Backup Operator" , "00c29273-979b-4161-815c-10b084fb9324" },
            { "Backup Reader" , "a795c7a0-d4a2-40c1-ae25-d81f01202912" },
            { "Classic Storage Account Contributor" , "86e8f5dc-a6e9-4c67-9d15-de283e8eac25" },
            { "Classic Storage Account Key Operator Service Role" , "985d6b00-f706-48f5-a6fe-d0ca12fb668d" },
            { "Data Box Contributor" , "add466c9-e687-43fc-8d98-dfcf8d720be5" },
            { "Data Box Reader" , "028f4ed7-e2a9-465e-a8f4-9c0ffdfdc027" },
            { "Data Lake Analytics Developer" , "47b7735b-770e-4598-a7da-8b91488b4c88" },
            { "Reader and Data Access" , "c12c1c16-33a1-487b-954d-41c89c60f349" },
            { "Storage Account Contributor" , "17d1049b-9a84-46fb-8f53-869881c3d3ab" },
            { "Storage Account Key Operator Service Role" , "81a9662b-bebf-436f-a333-f67b29880f12" },
            { "Storage Blob Data Contributor" , "ba92f5b4-2d11-453d-a403-e96b0029c9fe" },
            { "Storage Blob Data Owner" , "b7e6dc6d-f1e8-4753-8033-0f276bb0955b" },
            { "Storage Blob Data Reader" , "2a2b9908-6ea1-4ae2-8e65-a410df84e7d1" },
            { "Storage Blob Delegator" , "db58b8e5-c6ad-4a2a-8342-4190687cbf4a" },
            { "Storage File Data SMB Share Contributor" , "0c867c2a-1d8c-454a-a3db-ab2ea1bdc8bb" },
            { "Storage File Data SMB Share Elevated Contributor" , "a7264617-510b-434b-a828-9731dc254ea7" },
            { "Storage File Data SMB Share Reader" , "aba4ae5f-2193-4029-9191-0cb91df5e314" },
            { "Storage Queue Data Contributor" , "974c5e8b-45b9-4653-ba55-5f855dd0fb88" },
            { "Storage Queue Data Message Processor" , "8a0f0c08-91a1-4084-bc3d-661d67233fed" },
            { "Storage Queue Data Message Sender" , "c6a89b2d-59bc-44d0-9896-0f6e12d7b80a" },
            { "Storage Queue Data Reader" , "19e7f393-937e-4f77-808e-94535e297925" },
            { "Azure Maps Data Contributor" , "8f5e0ce6-4f7b-4dcf-bddf-e6f48634a204" },
            { "Azure Maps Data Reader" , "423170ca-a8f6-4b0f-8487-9e4eb8f49bfa" },
            { "Search Service Contributor" , "7ca78c08-252a-4471-8644-bb5ff32d4ba0" },
            { "SignalR AccessKey Reader" , "04165923-9d83-45d5-8227-78b77b0a687e" },
            { "SignalR App Server (Preview)" , "420fcaa2-552c-430f-98ca-3264be4806c7" },
            { "SignalR Contributor" , "8cf5e20a-e4b2-4e9d-b3a1-5ceb692c2761" },
            { "SignalR Serverless Contributor (Preview)" , "fd53cd77-2268-407a-8f46-7e7863d0f521" },
            { "SignalR Service Owner (Preview)" , "7e4f1700-ea5a-4f59-8f37-079cfe29dce3" },
            { "SignalR Service Reader (Preview)" , "ddde6b66-c0df-4114-a159-3618637b3035" },
            { "Web Plan Contributor" , "2cc479cb-7b4d-49a8-b449-8c00fd0f0a4b" },
            { "Website Contributor" , "de139f84-1756-47ae-9be6-808fbbe84772" },
            { "AcrDelete" , "c2f4ef07-c644-48eb-af81-4b1b4947fb11" },
            { "AcrImageSigner" , "6cef56e8-d556-48e5-a04f-b8e64114680f" },
            { "AcrPull" , "7f951dda-4ed3-4680-a7ca-43fe172d538d" },
            { "AcrPush" , "8311e382-0749-4cb8-b61a-304f252e45ec" },
            { "AcrQuarantineReader" , "cdda3590-29a3-44f6-95f2-9f980659eb04" },
            { "AcrQuarantineWriter" , "c8d4ff99-41c3-41a8-9f60-21dfdad59608" },
            { "Azure Kubernetes Service Cluster Admin Role" , "0ab0b1a8-8aac-4efd-b8c2-3ee1fb270be8" },
            { "Azure Kubernetes Service Cluster User Role" , "4abbcc35-e782-43d8-92c5-2d3f1bd2253f" },
            { "Azure Kubernetes Service Contributor Role" , "ed7f3fbd-7b88-4dd4-9017-9adb7ce333f8" },
            { "Azure Kubernetes Service RBAC Admin" , "3498e952-d568-435e-9b2c-8d77e338d7f7" },
            { "Azure Kubernetes Service RBAC Cluster Admin" , "b1ff04bb-8a4e-4dc4-8eb5-8693973ce19b" },
            { "Azure Kubernetes Service RBAC Reader" , "7f6c6a51-bcf8-42ba-9220-52d62157d7db" },
            { "Azure Kubernetes Service RBAC Writer" , "a7ffa36f-339b-4b5c-8bdf-e2c188b2c0eb" },
            { "Cosmos DB Account Reader Role" , "fbdf93bf-df7d-467e-a4d2-9458aa1360c8" },
            { "Cosmos DB Operator" , "230815da-be43-4aae-9cb4-875f7bd000aa" },
            { "CosmosBackupOperator" , "db7b14f2-5adf-42da-9f96-f2ee17bab5cb" },
            { "CosmosRestoreOperator" , "5432c526-bc82-444a-b7ba-57c5b0b5b34f" },
            { "DocumentDB Account Contributor" , "5bd9cd88-fe45-4216-938b-f97437e15450" },
            { "Redis Cache Contributor" , "e0f68234-74aa-48ed-b826-c38b57376e17" },
            { "SQL DB Contributor" , "9b7fa17d-e63e-47b0-bb0a-15c516ac86ec" },
            { "SQL Managed Instance Contributor" , "4939a1f6-9ae0-4e48-a1e0-f2cbe897382d" },
            { "SQL Security Manager" , "056cd41c-7e88-42e1-933e-88ba6a50c9c3" },
            { "SQL Server Contributor" , "6d8ee4ec-f05a-4a1d-8b00-a9b17e38b437" },
            { "Azure Event Hubs Data Owner" , "f526a384-b230-433a-b45c-95f59c4a2dec" },
            { "Azure Event Hubs Data Receiver" , "a638d3c7-ab3a-418d-83e6-5f17a39d4fde" },
            { "Azure Event Hubs Data Sender" , "2b629674-e913-4c01-ae53-ef4638d8f975" },
            { "Data Factory Contributor" , "673868aa-7521-48a0-acc6-0f60742d39f5" },
            { "Data Purger" , "150f5e0c-0603-4f03-8c7f-cf70034c4e90" },
            { "HDInsight Cluster Operator" , "61ed4efc-fab3-44fd-b111-e24485cc132a" },
            { "HDInsight Domain Services Contributor" , "8d8d5a11-05d3-4bda-a417-a08778121c7c" },
            { "Log Analytics Contributor" , "92aaf0da-9dab-42b6-94a3-d43ce8d16293" },
            { "Log Analytics Reader" , "73c42c96-874c-492b-b04d-ab87d138a893" },
            { "Purview Data Curator" , "8a3c2885-9b38-4fd2-9d99-91af537c1347" },
            { "Purview Data Reader" , "ff100721-1b9d-43d8-af52-42b69c1272db" },
            { "Purview Data Source Administrator" , "200bba9e-f0c8-430f-892b-6f0794863803" },
            { "Schema Registry Contributor (Preview)" , "5dffeca3-4936-4216-b2bc-10343a5abb25" },
            { "Schema Registry Reader (Preview)" , "2c56ea50-c6b3-40a6-83c0-9d98858bc7d2" },
            { "Blockchain Member Node Access (Preview)" , "31a002a1-acaf-453e-8a5b-297c9ca1ea24" },
            { "Cognitive Services Contributor" , "25fbc0a9-bd7c-42a3-aa1a-3b75d497ee68" },
            { "Cognitive Services Custom Vision Contributor" , "c1ff6cc2-c111-46fe-8896-e0ef812ad9f3" },
            { "Cognitive Services Custom Vision Deployment" , "5c4089e1-6d96-4d2f-b296-c1bc7137275f" },
            { "Cognitive Services Custom Vision Labeler" , "88424f51-ebe7-446f-bc41-7fa16989e96c" },
            { "Cognitive Services Custom Vision Reader" , "93586559-c37d-4a6b-ba08-b9f0940c2d73" },
            { "Cognitive Services Custom Vision Trainer" , "0a5ae4ab-0d65-4eeb-be61-29fc9b54394b" },
            { "Cognitive Services Data Reader (Preview)" , "b59867f0-fa02-499b-be73-45a86b5b3e1c" },
            { "Cognitive Services Metrics Advisor Administrator" , "cb43c632-a144-4ec5-977c-e80c4affc34a" },
            { "Cognitive Services QnA Maker Editor" , "f4cc2bf9-21be-47a1-bdf1-5c5804381025" },
            { "Cognitive Services QnA Maker Reader" , "466ccd10-b268-4a11-b098-b4849f024126" },
            { "Cognitive Services User" , "a97b65f3-24c7-4388-baec-2e87135dc908" },
            { "Device Update Administrator" , "02ca0879-e8e4-47a5-a61e-5c618b76e64a" },
            { "Device Update Content Administrator" , "0378884a-3af5-44ab-8323-f5b22f9f3c98" },
            { "Device Update Content Reader" , "d1ee9a80-8b14-47f0-bdc2-f4a351625a7b" },
            { "Device Update Deployments Administrator" , "e4237640-0e3d-4a46-8fda-70bc94856432" },
            { "Device Update Deployments Reader" , "49e2f5d2-7741-4835-8efa-19e1fe35e47f" },
            { "Device Update Reader" , "e9dba6fb-3d52-4cf0-bce3-f06ce71b9e0f" },
            { "Remote Rendering Administrator" , "3df8b902-2a6f-47c7-8cc5-360e9b272a7e" },
            { "Remote Rendering Client" , "d39065c4-c120-43c9-ab0a-63eed9795f0a" },
            { "Spatial Anchors Account Contributor" , "8bbe83f1-e2a6-4df7-8cb4-4e04d4e5c827" },
            { "Spatial Anchors Account Owner" , "70bbe301-9835-447d-afdd-19eb3167307c" },
            { "Spatial Anchors Account Reader" , "5d51204f-eb77-4b1c-b86a-2ec626c49413" },
            { "API Management Service Contributor" , "312a565d-c81f-4fd8-895a-4e21e48d571c" },
            { "API Management Service Operator Role" , "e022efe7-f5ba-4159-bbe4-b44f577e9b61" },
            { "API Management Service Reader Role" , "71522526-b88f-4d52-b57f-d31fc3546d0d" },
            { "App Configuration Data Owner" , "5ae67dd6-50cb-40e7-96ff-dc2bfa4b606b" },
            { "App Configuration Data Reader" , "516239f1-63e1-4d78-a4de-a74fb236a071" },
            { "Azure Service Bus Data Owner" , "090c5cfd-751d-490a-894a-3ce6f1109419" },
            { "Azure Service Bus Data Receiver" , "4f6d3b9b-027b-4f4c-9142-0e5a2a2247e0" },
            { "Azure Service Bus Data Sender" , "69a216fc-b8fb-44d8-bc22-1f3c2cd27a39" },
            { "Azure Stack Registration Owner" , "6f12a6df-dd06-4f3e-bcb1-ce8be600526a" },
            { "EventGrid Contributor" , "1e241071-0855-49ea-94dc-649edcd759de" },
            { "EventGrid EventSubscription Contributor" , "428e0ff0-5e57-4d9c-a221-2c70d0e0a443" },
            { "EventGrid EventSubscription Reader" , "2414bbcf-6497-4faf-8c65-045460748405" },
            { "FHIR Data Contributor" , "5a1fc7df-4bf1-4951-a576-89034ee01acd" },
            { "FHIR Data Exporter" , "3db33094-8700-4567-8da5-1501d4e7e843" },
            { "FHIR Data Reader" , "4c8d0bbc-75d3-4935-991f-5f3c56d81508" },
            { "FHIR Data Writer" , "3f88fce4-5892-4214-ae73-ba5294559913" },
            { "Integration Service Environment Contributor" , "a41e2c5b-bd99-4a07-88f4-9bf657a760b8" },
            { "Integration Service Environment Developer" , "c7aa55d3-1abb-444a-a5ca-5e51e485d6ec" },
            { "Intelligent Systems Account Contributor" , "03a6d094-3444-4b3d-88af-7477090a9e5e" },
            { "Logic App Contributor" , "87a39d53-fc1b-424a-814c-f7e04687dc9e" },
            { "Logic App Operator" , "515c2055-d9d4-4321-b1b9-bd0c9a0f79fe" },
            { "Managed Identity Contributor" , "e40ec5ca-96e0-45a2-b4ff-59039f2c2b59" },
            { "Managed Identity Operator" , "f1a07417-d97a-45cb-824c-7a7467783830" },
            { "Attestation Contributor" , "bbf86eb8-f7b4-4cce-96e4-18cddf81d86e" },
            { "Attestation Reader" , "fd1bd22b-8476-40bc-a0bc-69b95687b9f3" },
            { "Azure Sentinel Contributor" , "ab8e14d6-4a74-4a29-9ba8-549422addade" },
            { "Azure Sentinel Reader" , "8d289c81-5878-46d4-8554-54e1e3d8b5cb" },
            { "Azure Sentinel Responder" , "3e150937-b8fe-4cfb-8069-0eaf05ecd056" },
            { "Key Vault Administrator" , "00482a5a-887f-4fb3-b363-3b7fe8e74483" },
            { "Key Vault Certificates Officer" , "a4417e6f-fecd-4de8-b567-7b0420556985" },
            { "Key Vault Contributor" , "f25e0fa2-a7c8-4377-a976-54943a77a395" },
            { "Key Vault Crypto Officer" , "14b46e9e-c2b7-41b4-b07b-48a6ebf60603" },
            { "Key Vault Crypto Service Encryption User" , "e147488a-f6f5-4113-8e2d-b22465e65bf6" },
            { "Key Vault Crypto User" , "12338af0-0e69-4776-bea7-57ae8d297424" },
            { "Key Vault Reader" , "21090545-7ca7-4776-b22c-e363652d74d2" },
            { "Key Vault Secrets Officer" , "b86a8fe4-44ce-4948-aee5-eccb2c155cd7" },
            { "Key Vault Secrets User" , "4633458b-17de-408a-b874-0445c86b69e6" },
            { "Managed HSM contributor" , "18500a29-7fe2-46b2-a342-b16a415e101d" },
            { "Security Admin" , "fb1c8493-542b-48eb-b624-b4c8fea62acd" },
            { "Security Assessment Contributor" , "612c2aa1-cb24-443b-ac28-3ab7272de6f5" },
            { "Security Manager (Legacy)" , "e3d13bf0-dd5a-482e-ba6b-9b8433878d10" },
            { "Security Reader" , "39bc4728-0917-49c7-9d2c-d95423bc2eb4" },
            { "DevTest Labs User" , "76283e04-6283-4c54-8f91-bcf1374a3c64" },
            { "Lab Creator" , "b97fb8bc-a8b2-4522-a38b-dd33c7e65ead" },
            { "Application Insights Component Contributor" , "ae349356-3a1b-4a5e-921d-050484c6347e" },
            { "Application Insights Snapshot Debugger" , "08954f03-6346-4c2e-81c0-ec3a5cfae23b" },
            { "Monitoring Contributor" , "749f88d5-cbae-40b8-bcfc-e573ddc772fa" },
            { "Monitoring Metrics Publisher" , "3913510d-42f4-4e42-8a64-420c390055eb" },
            { "Monitoring Reader" , "43d0d8ad-25c7-4714-9337-8ba259a9fe05" },
            { "Workbook Contributor" , "e8ddcd69-c73f-4f9f-9844-4100522f16ad" },
            { "Workbook Reader" , "b279062a-9be3-42a0-92ae-8b3cf002ec4d" },
            { "Automation Job Operator" , "4fe576fe-1146-4730-92eb-48519fa6bf9f" },
            { "Automation Operator" , "d3881f73-407a-4167-8283-e981cbba0404" },
            { "Automation Runbook Operator" , "5fb5aef8-1081-4b8e-bb16-9d5d0385bab5" },
            { "Azure Connected Machine Onboarding" , "b64e21ea-ac4e-4cdf-9dc9-5b892992bee7" },
            { "Azure Connected Machine Resource Administrator" , "cd570a14-e51a-42ad-bac8-bafd67325302" },
            { "Billing Reader" , "fa23ad8b-c56e-40d8-ac0c-ce449e1d2c64" },
            { "Blueprint Contributor" , "41077137-e803-4205-871c-5a86e6a753b4" },
            { "Blueprint Operator" , "437d2ced-4a38-4302-8479-ed2bcb43d090" },
            { "Cost Management Contributor" , "434105ed-43f6-45c7-a02f-909b2ba83430" },
            { "Cost Management Reader" , "72fafb9e-0641-4937-9268-a91bfd8191a3" },
            { "Hierarchy Settings Administrator" , "350f8d15-c687-4448-8ae1-157740a3936d" },
            { "Kubernetes Cluster - Azure Arc Onboarding" , "34e09817-6cbe-4d01-b1a2-e0eac5743d41" },
            { "Managed Application Contributor Role" , "641177b8-a67a-45b9-a033-47bc880bb21e" },
            { "Managed Application Operator Role" , "c7393b34-138c-406f-901b-d8cf2b17e6ae" },
            { "Managed Applications Reader" , "b9331d33-8a36-4f8c-b097-4f54124fdb44" },
            { "Managed Services Registration assignment Delete Role" , "91c1777a-f3dc-4fae-b103-61d183457e46" },
            { "Management Group Contributor" , "5d58bcaf-24a5-4b20-bdb6-eed9f69fbe4c" },
            { "Management Group Reader" , "ac63b705-f282-497d-ac71-919bf39d939d" },
            { "New Relic APM Account Contributor" , "5d28c62d-5b37-4476-8438-e587778df237" },
            { "Policy Insights Data Writer (Preview)" , "66bb4e9e-b016-4a94-8249-4c0511c2be84" },
            { "Quota Request Operator Role" , "0e5f05e5-9ab9-446b-b98d-1e2157c94125" },
            { "Reservation Purchaser" , "f7b75c60-3036-4b75-91c3-6b41c27c1689" },
            { "Resource Policy Contributor" , "36243c78-bf99-498c-9df9-86d9f8d28608" },
            { "Site Recovery Contributor" , "6670b86e-a3f7-4917-ac9b-5d6ab1be4567" },
            { "Site Recovery Operator" , "494ae006-db33-4328-bf46-533a6560a3ca" },
            { "Site Recovery Reader" , "dbaa88c4-0c30-4179-9fb3-46319faa6149" },
            { "Support Request Contributor" , "cfd33db0-3dd1-45e3-aa9d-cdbdf3b6f24e" },
            { "Tag Contributor" , "4a9ae827-6dc8-4573-8ac7-8239d42aa03f" },
            { "Azure Digital Twins Data Owner" , "bcd981a7-7f74-457b-83e1-cceb9e632ffe" },
            { "Azure Digital Twins Data Reader" , "d57506d4-4c8d-48b1-8587-93c323f6a5a3" },
            { "BizTalk Contributor" , "5e3c6656-6cfa-4708-81fe-0de47ac73342" },
            { "Desktop Virtualization Application Group Contributor" , "86240b0e-9422-4c43-887b-b61143f32ba8" },
            { "Desktop Virtualization Application Group Reader" , "aebf23d0-b568-4e86-b8f9-fe83a2c6ab55" },
            { "Desktop Virtualization Contributor" , "082f0a83-3be5-4ba1-904c-961cca79b387" },
            { "Desktop Virtualization Host Pool Contributor" , "e307426c-f9b6-4e81-87de-d99efb3c32bc" },
            { "Desktop Virtualization Host Pool Reader" , "ceadfde2-b300-400a-ab7b-6143895aa822" },
            { "Desktop Virtualization Reader" , "49a72310-ab8d-41df-bbb0-79b649203868" },
            { "Desktop Virtualization Session Host Operator" , "2ad6aaab-ead9-4eaa-8ac5-da422f562408" },
            { "Desktop Virtualization User" , "1d18fff3-a72a-46b5-b4a9-0b38a3cd7e63" },
            { "Desktop Virtualization User Session Operator" , "ea4bfff8-7fb4-485a-aadd-d4129a0ffaa6" },
            { "Desktop Virtualization Workspace Contributor" , "21efdde3-836f-432b-bf3d-3e8e734d4b2b" },
            { "Desktop Virtualization Workspace Reader" , "0fa44ee9-7a7d-466b-9bb2-2bf446b1204d" },
            { "Disk Backup Reader" , "3e5e47e6-65f7-47ef-90b5-e5dd4d455f24" },
            { "Disk Restore Operator" , "b50d9833-a0cb-478e-945f-707fcc997c13" },
            { "Disk Snapshot Contributor" , "7efff54f-a5b4-42b5-a1c5-5411624893ce" },
            { "Scheduler Job Collections Contributor" , "188a0f2f-5c9e-469b-ae67-2aa5ce574b94" },
            { "Services Hub Operator" , "82200a5b-e217-47a5-b665-6d8765ee745b" }
        };
    }
}